// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeAnalyzer.Api.Data;

#nullable disable

namespace ResumeAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622000000_SchemaQuickWins")]
    partial class SchemaQuickWins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAnalyzer.Api.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("MatchLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<List<string>>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ResumeFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResumeFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResumeText")
                        .HasColumnType("text");

                    b.Property<List<string>>("Strengths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Analyses_UserId_CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Analyses", t =>
                        {
                            t.HasCheckConstraint("CK_Analyses_MatchScore_Range", "\"MatchScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ResumeAnalyzer.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ResumeAnalyzer.Api.Models.Analysis", b =>
                {
                    b.HasOne("ResumeAnalyzer.Api.Models.User", "User")
                        .WithMany("Analyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeAnalyzer.Api.Models.User", b =>
                {
                    b.Navigation("Analyses");
                });
#pragma warning restore 612, 618
        }
    }
}
